CREATE TABLE public.affiliate_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  affiliate_user_id uuid NOT NULL,
  code text NOT NULL CHECK (code ~ '^[A-Za-z0-9_-]{3,40}$'::text),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT affiliate_codes_pkey PRIMARY KEY (id),
  CONSTRAINT affiliate_codes_affiliate_user_id_fkey FOREIGN KEY (affiliate_user_id) REFERENCES public.profiles(id)
);



CREATE TABLE public.affiliate_commission_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  affiliate_user_id uuid NOT NULL,
  referred_user_id uuid NOT NULL,
  provider_ledger_entry_id uuid,
  revenue_event_id text NOT NULL,
  base_amount numeric NOT NULL,
  commission_bps integer NOT NULL CHECK (commission_bps >= 0 AND commission_bps <= 10000),
  commission_amount numeric NOT NULL,
  currency text NOT NULL DEFAULT 'usd'::text,
  status text NOT NULL DEFAULT 'pending_hold'::text CHECK (status = ANY (ARRAY['pending_hold'::text, 'payable'::text, 'paid'::text, 'reversed'::text])),
  payable_after timestamp with time zone,
  payout_batch_id uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT affiliate_commission_events_pkey PRIMARY KEY (id),
  CONSTRAINT affiliate_commission_events_affiliate_user_id_fkey FOREIGN KEY (affiliate_user_id) REFERENCES public.profiles(id),
  CONSTRAINT affiliate_commission_events_referred_user_id_fkey FOREIGN KEY (referred_user_id) REFERENCES public.profiles(id),
  CONSTRAINT affiliate_commission_events_provider_ledger_entry_id_fkey FOREIGN KEY (provider_ledger_entry_id) REFERENCES public.provider_ledger_entries(id),
  CONSTRAINT affiliate_commission_events_payout_batch_id_fkey FOREIGN KEY (payout_batch_id) REFERENCES public.affiliate_payout_batches(id)
);
CREATE TABLE public.affiliate_payout_batches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  period_start date NOT NULL,
  period_end date NOT NULL,
  currency text NOT NULL DEFAULT 'usd'::text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'locked'::text, 'processed'::text, 'failed'::text])),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  processed_at timestamp with time zone,
  CONSTRAINT affiliate_payout_batches_pkey PRIMARY KEY (id)
);
CREATE TABLE public.affiliate_payout_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  batch_id uuid NOT NULL,
  affiliate_user_id uuid NOT NULL,
  gross_amount numeric NOT NULL,
  adjustments_amount numeric NOT NULL DEFAULT 0,
  net_amount numeric NOT NULL,
  currency text NOT NULL DEFAULT 'usd'::text,
  status text NOT NULL DEFAULT 'locked'::text CHECK (status = ANY (ARRAY['locked'::text, 'credited'::text, 'skipped'::text])),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT affiliate_payout_items_pkey PRIMARY KEY (id),
  CONSTRAINT affiliate_payout_items_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.affiliate_payout_batches(id),
  CONSTRAINT affiliate_payout_items_affiliate_user_id_fkey FOREIGN KEY (affiliate_user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.affiliate_profiles (
  user_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['pending'::text, 'active'::text, 'suspended'::text])),
  default_commission_bps integer NOT NULL DEFAULT 500 CHECK (default_commission_bps >= 0 AND default_commission_bps <= 10000),
  hold_days integer NOT NULL DEFAULT 30 CHECK (hold_days >= 0 AND hold_days <= 365),
  minimum_withdrawal_amount numeric NOT NULL DEFAULT 10.00,
  payout_currency text NOT NULL DEFAULT 'usd'::text,
  payout_details jsonb NOT NULL DEFAULT '{}'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT affiliate_profiles_pkey PRIMARY KEY (user_id),
  CONSTRAINT affiliate_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.affiliate_wallet_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  affiliate_user_id uuid NOT NULL,
  kind text NOT NULL CHECK (kind = ANY (ARRAY['payout_credit'::text, 'withdrawal_debit'::text, 'adjustment_credit'::text, 'adjustment_debit'::text])),
  amount numeric NOT NULL,
  currency text NOT NULL DEFAULT 'usd'::text,
  reference_type text,
  reference_id text,
  note text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT affiliate_wallet_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT affiliate_wallet_transactions_affiliate_user_id_fkey FOREIGN KEY (affiliate_user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.affiliate_withdrawal_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  affiliate_user_id uuid NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  currency text NOT NULL DEFAULT 'usd'::text,
  status text NOT NULL DEFAULT 'requested'::text CHECK (status = ANY (ARRAY['requested'::text, 'processing'::text, 'paid'::text, 'failed'::text, 'canceled'::text])),
  payout_reference text,
  failure_reason text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  requested_at timestamp with time zone NOT NULL DEFAULT now(),
  processed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT affiliate_withdrawal_requests_pkey PRIMARY KEY (id),
  CONSTRAINT affiliate_withdrawal_requests_affiliate_user_id_fkey FOREIGN KEY (affiliate_user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.booking_live_locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL UNIQUE,
  provider_id uuid NOT NULL,
  latitude double precision NOT NULL CHECK (latitude >= '-90'::integer::double precision AND latitude <= 90::double precision),
  longitude double precision NOT NULL CHECK (longitude >= '-180'::integer::double precision AND longitude <= 180::double precision),
  accuracy_meters double precision,
  heading_degrees double precision,
  speed_mps double precision,
  captured_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT booking_live_locations_pkey PRIMARY KEY (id),
  CONSTRAINT booking_live_locations_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_live_locations_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.booking_offers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  thread_id uuid NOT NULL,
  booking_id uuid NOT NULL,
  service_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  provider_id uuid NOT NULL,
  created_by uuid NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  currency text NOT NULL DEFAULT 'usd'::text,
  scope_note text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text, 'expired'::text, 'canceled'::text, 'superseded'::text, 'payment_failed'::text])),
  expires_at timestamp with time zone,
  accepted_at timestamp with time zone,
  declined_at timestamp with time zone,
  canceled_at timestamp with time zone,
  superseded_by_offer_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT booking_offers_pkey PRIMARY KEY (id),
  CONSTRAINT booking_offers_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES public.threads(id),
  CONSTRAINT booking_offers_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_offers_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT booking_offers_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.profiles(id),
  CONSTRAINT booking_offers_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.profiles(id),
  CONSTRAINT booking_offers_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT booking_offers_superseded_by_offer_id_fkey FOREIGN KEY (superseded_by_offer_id) REFERENCES public.booking_offers(id)
);
CREATE TABLE public.booking_status_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  from_status text,
  to_status text NOT NULL,
  changed_by uuid,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  note text,
  CONSTRAINT booking_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT booking_status_history_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_status_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.booking_team_assignment_offers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assignment_id uuid NOT NULL,
  offered_member_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text, 'expired'::text])),
  responded_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT booking_team_assignment_offers_pkey PRIMARY KEY (id),
  CONSTRAINT booking_team_assignment_offers_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.booking_team_assignments(id),
  CONSTRAINT booking_team_assignment_offers_offered_member_id_fkey FOREIGN KEY (offered_member_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.booking_team_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  owner_id uuid NOT NULL,
  assignment_type text NOT NULL CHECK (assignment_type = ANY (ARRAY['member'::text, 'group'::text, 'team_pool'::text])),
  target_member_id uuid,
  target_group_id uuid,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'pending_offer'::text, 'accepted'::text, 'declined'::text, 'cancelled'::text, 'completed'::text])),
  expires_at timestamp with time zone,
  accepted_member_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  delegated_note text CHECK (delegated_note IS NULL OR char_length(delegated_note) <= 500),
  applied_owner_share numeric CHECK (applied_owner_share IS NULL OR applied_owner_share >= 0::numeric AND applied_owner_share <= 100::numeric),
  CONSTRAINT booking_team_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT booking_team_assignments_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_team_assignments_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.profiles(id),
  CONSTRAINT booking_team_assignments_target_member_id_fkey FOREIGN KEY (target_member_id) REFERENCES public.profiles(id),
  CONSTRAINT booking_team_assignments_target_group_id_fkey FOREIGN KEY (target_group_id) REFERENCES public.provider_team_groups(id)
);
CREATE TABLE public.booking_tips (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL UNIQUE,
  customer_id uuid NOT NULL,
  provider_id uuid NOT NULL,
  amount_cents integer NOT NULL CHECK (amount_cents > 0),
  currency text NOT NULL DEFAULT 'usd'::text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text, 'refunded'::text])),
  stripe_payment_intent_id text UNIQUE,
  stripe_charge_id text,
  payment_method_record_id uuid,
  failure_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT booking_tips_pkey PRIMARY KEY (id),
  CONSTRAINT booking_tips_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_tips_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.profiles(id),
  CONSTRAINT booking_tips_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.profiles(id),
  CONSTRAINT booking_tips_payment_method_record_id_fkey FOREIGN KEY (payment_method_record_id) REFERENCES public.customer_payment_methods(id)
);
CREATE TABLE public.booking_verifications (
  booking_id uuid NOT NULL,
  verification_required boolean NOT NULL DEFAULT false,
  customer_to_provider_code_hash text,
  customer_to_provider_code_expires_at timestamp with time zone,
  customer_to_provider_attempts integer NOT NULL DEFAULT 0,
  customer_to_provider_verified_at timestamp with time zone,
  provider_to_customer_code_hash text,
  provider_to_customer_code_expires_at timestamp with time zone,
  provider_to_customer_attempts integer NOT NULL DEFAULT 0,
  provider_to_customer_verified_at timestamp with time zone,
  verification_completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT booking_verifications_pkey PRIMARY KEY (booking_id),
  CONSTRAINT booking_verifications_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL,
  provider_id uuid NOT NULL,
  service_id uuid NOT NULL,
  scheduled_date date NOT NULL,
  scheduled_start_time time without time zone NOT NULL,
  scheduled_end_time time without time zone NOT NULL,
  address text,
  latitude double precision,
  longitude double precision,
  notes_from_customer text,
  booking_status text NOT NULL DEFAULT 'pending'::text CHECK (booking_status = ANY (ARRAY['pending'::text, 'accepted'::text, 'on_the_way'::text, 'arrived'::text, 'declined'::text, 'canceled_by_customer'::text, 'canceled_by_provider'::text, 'in_progress'::text, 'awaiting_confirmation'::text, 'completed'::text, 'no_show'::text])),
  payment_status text NOT NULL DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'authorized'::text, 'paid'::text, 'in_escrow'::text, 'released'::text, 'refunded'::text])),
  total_price numeric NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  started_at timestamp with time zone,
  provider_marked_done_at timestamp with time zone,
  completed_at timestamp with time zone,
  canceled_at timestamp with time zone,
  cancellation_reason text,
  provider_live_state text CHECK (provider_live_state IS NULL OR (provider_live_state = ANY (ARRAY['accepted'::text, 'on_the_way'::text, 'arrived'::text, 'in_progress'::text, 'awaiting_confirmation'::text, 'completed'::text]))),
  arrived_at timestamp with time zone,
  service_started_at timestamp with time zone,
  auto_completed_at timestamp with time zone,
  before_image_urls ARRAY NOT NULL DEFAULT '{}'::text[],
  after_image_urls ARRAY NOT NULL DEFAULT '{}'::text[],
  stripe_payment_intent_id text,
  stripe_payment_method_id text,
  stripe_charge_id text,
  acceptance_source text CHECK (acceptance_source IS NULL OR (acceptance_source = ANY (ARRAY['direct'::text, 'delegated_member'::text, 'delegated_group'::text, 'delegated_team_pool'::text]))),
  accepted_via_assignment_id uuid,
  accepted_offer_id uuid,
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.profiles(id),
  CONSTRAINT bookings_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.profiles(id),
  CONSTRAINT bookings_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT bookings_accepted_via_assignment_id_fkey FOREIGN KEY (accepted_via_assignment_id) REFERENCES public.booking_team_assignments(id),
  CONSTRAINT bookings_accepted_offer_id_fkey FOREIGN KEY (accepted_offer_id) REFERENCES public.booking_offers(id)
);
CREATE TABLE public.booster_types (
  id text NOT NULL,
  name text NOT NULL,
  description text,
  icon text,
  base_points_cost integer NOT NULL CHECK (base_points_cost > 0),
  min_duration_hours integer NOT NULL CHECK (min_duration_hours > 0),
  max_duration_hours integer NOT NULL CHECK (max_duration_hours > 0),
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT booster_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.customer_kyc_verifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  provider text NOT NULL DEFAULT 'stripe_identity'::text CHECK (provider = ANY (ARRAY['stripe_identity'::text])),
  verification_session_id text NOT NULL UNIQUE,
  verification_report_id text,
  status text NOT NULL DEFAULT 'created'::text CHECK (status = ANY (ARRAY['created'::text, 'processing'::text, 'verified'::text, 'requires_input'::text, 'canceled'::text, 'redacted'::text])),
  last_error_code text,
  last_error_message text,
  redacted_at timestamp with time zone,
  verified_at timestamp with time zone,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT customer_kyc_verifications_pkey PRIMARY KEY (id),
  CONSTRAINT customer_kyc_verifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.customer_payment_methods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  stripe_customer_id text NOT NULL,
  stripe_payment_method_id text NOT NULL UNIQUE,
  type text NOT NULL DEFAULT 'card'::text,
  card_brand text,
  card_last4 text,
  card_exp_month integer,
  card_exp_year integer,
  is_default boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT customer_payment_methods_pkey PRIMARY KEY (id),
  CONSTRAINT customer_payment_methods_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.favorites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  service_id uuid,
  provider_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT favorites_pkey PRIMARY KEY (id),
  CONSTRAINT favorites_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT favorites_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT favorites_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  thread_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  text text NOT NULL,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  client_id uuid,
  attachment_path text,
  attachment_mime text,
  attachment_size_bytes bigint,
  message_type text NOT NULL DEFAULT 'text'::text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES public.threads(id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.notification_devices (
id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY  user_id uuid NOT NULL,
  token text NOT NULL,
  platform text NOT NULL DEFAULT 'android'::text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  app_state text DEFAULT 'background'::text,
  last_seen_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_devices_pkey PRIMARY KEY (id),
  CONSTRAINT notification_devices_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.package_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  package_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  provider_id uuid NOT NULL,
  subscription_status text NOT NULL DEFAULT 'active'::text CHECK (subscription_status = ANY (ARRAY['active'::text, 'paused'::text, 'cancelled'::text, 'completed'::text])),
  start_date timestamp with time zone NOT NULL,
  next_payment_date timestamp with time zone,
  payments_completed integer DEFAULT 0,
  payments_remaining integer,
  total_paid numeric DEFAULT 0,
  payment_method_id text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT package_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT package_subscriptions_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.packages(id),
  CONSTRAINT package_subscriptions_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.profiles(id),
  CONSTRAINT package_subscriptions_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.packages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  service_id uuid NOT NULL,
  package_name text NOT NULL,
  original_price numeric NOT NULL,
  payment_structure text NOT NULL CHECK (payment_structure = ANY (ARRAY['one_time'::text, 'weekly'::text, 'monthly'::text])),
  installment_amount numeric NOT NULL,
  number_of_payments integer NOT NULL,
  total_package_price numeric NOT NULL,
  duration_weeks integer,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  description text,
  terms text,
  cancellation_policy text,
  max_subscribers integer,
  current_subscribers integer DEFAULT 0,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'paused'::text, 'inactive'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT packages_pkey PRIMARY KEY (id),
  CONSTRAINT packages_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.profiles(id),
  CONSTRAINT packages_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.payment_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  booking_id uuid,
  provider_id uuid,
  event_source text NOT NULL DEFAULT 'stripe'::text,
  event_type text NOT NULL,
  stripe_event_id text UNIQUE,
  stripe_object_id text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  processed_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_events_pkey PRIMARY KEY (id),
  CONSTRAINT payment_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT payment_events_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT payment_events_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.pending_referral_claims (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  app_instance_id text NOT NULL,
  device_fingerprint text,
  affiliate_user_id uuid NOT NULL,
  click_id text,
  source text NOT NULL CHECK (source = ANY (ARRAY['deep_link'::text, 'android_referrer'::text, 'ios_deferred'::text, 'manual_code'::text, 'unknown'::text])),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_consumed boolean NOT NULL DEFAULT false,
  consumed_at timestamp with time zone,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pending_referral_claims_pkey PRIMARY KEY (id),
  CONSTRAINT pending_referral_claims_affiliate_user_id_fkey FOREIGN KEY (affiliate_user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.point_packages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  points_amount integer NOT NULL CHECK (points_amount > 0),
  bonus_points integer DEFAULT 0 CHECK (bonus_points >= 0),
  price_cents integer NOT NULL CHECK (price_cents > 0),
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT point_packages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.point_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  package_id uuid,
  points_amount integer NOT NULL CHECK (points_amount > 0),
  amount_cents integer NOT NULL CHECK (amount_cents >= 0),
  bonus_points integer DEFAULT 0,
  payment_method text NOT NULL CHECK (payment_method = ANY (ARRAY['card'::text, 'wallet'::text])),
  stripe_payment_intent_id text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text, 'refunded'::text])),
  failure_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT point_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT point_transactions_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.profiles(id),
  CONSTRAINT point_transactions_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.point_packages(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  role text NOT NULL DEFAULT 'customer'::text CHECK (role = ANY (ARRAY['customer'::text, 'provider'::text, 'both'::text])),
  first_name text,
  last_name text,
  email text,
  phone_number text,
  profile_photo_url text,
  bio text,
  location_city text,
  location_state text,
  location_country text,
  primary_address text,
  latitude double precision,
  longitude double precision,
  rating_average double precision DEFAULT 0,
  rating_count integer DEFAULT 0,
  is_verified_provider boolean DEFAULT false,
  verification_status text DEFAULT 'not_started'::text CHECK (verification_status = ANY (ARRAY['not_started'::text, 'pending'::text, 'approved'::text, 'rejected'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  version bigint,
  stripe_customer_id text UNIQUE,
  public_profile_id text NOT NULL CHECK (public_profile_id ~ '^[a-z0-9._]{3,30}$'::text),
  public_profile_id_version smallint NOT NULL DEFAULT 1,
  default_delegated_owner_share numeric DEFAULT 70.00 CHECK (default_delegated_owner_share >= 0::numeric AND default_delegated_owner_share <= 100::numeric),
  instagram_handle text CHECK (instagram_handle IS NULL OR instagram_handle ~ '^[a-z0-9._]+$'::text),
  instagram_verified boolean NOT NULL DEFAULT false,
  instagram_verified_at timestamp with time zone,
  tiktok_handle text CHECK (tiktok_handle IS NULL OR tiktok_handle ~ '^[a-z0-9._]+$'::text),
  tiktok_verified boolean NOT NULL DEFAULT false,
  tiktok_verified_at timestamp with time zone,
  username text NOT NULL CHECK (username ~ '^[a-z0-9._]{3,30}$'::text),
  availability_updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_available boolean NOT NULL DEFAULT true,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.provider_account_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  stripe_account_id text NOT NULL,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['detached_due_to_error'::text, 'manually_detached'::text, 'relinked'::text])),
  detected_by text NOT NULL,
  stripe_error_code text,
  stripe_error_message text,
  stripe_error_type text,
  stripe_error_param text,
  stripe_error_status integer,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT provider_account_history_pkey PRIMARY KEY (id),
  CONSTRAINT provider_account_history_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.provider_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL UNIQUE,
  stripe_account_id text UNIQUE,
  onboarding_status text NOT NULL DEFAULT 'not_started'::text CHECK (onboarding_status = ANY (ARRAY['not_started'::text, 'pending'::text, 'active'::text, 'restricted'::text])),
  charges_enabled boolean NOT NULL DEFAULT false,
  payouts_enabled boolean NOT NULL DEFAULT false,
  payout_mode text NOT NULL DEFAULT 'scheduled'::text CHECK (payout_mode = ANY (ARRAY['manual'::text, 'scheduled'::text, 'hybrid'::text])),
  payout_schedule text NOT NULL DEFAULT 'weekly'::text CHECK (payout_schedule = ANY (ARRAY['daily'::text, 'weekly'::text, 'biweekly'::text, 'monthly'::text])),
  minimum_withdrawal_amount numeric NOT NULL DEFAULT 10.00,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT provider_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT provider_accounts_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.provider_availability (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  service_id uuid,
  day_of_week integer CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone,
  end_time time without time zone,
  specific_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT provider_availability_pkey PRIMARY KEY (id),
  CONSTRAINT provider_availability_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.profiles(id),
  CONSTRAINT provider_availability_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.provider_boosters (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  booster_type text NOT NULL,
  points_spent integer NOT NULL CHECK (points_spent > 0),
  duration_hours integer NOT NULL CHECK (duration_hours > 0),
  starts_at timestamp with time zone NOT NULL,
  ends_at timestamp with time zone NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT provider_boosters_pkey PRIMARY KEY (id),
  CONSTRAINT provider_boosters_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.profiles(id),
  CONSTRAINT provider_boosters_booster_type_fkey FOREIGN KEY (booster_type) REFERENCES public.booster_types(id)
);
CREATE TABLE public.provider_delegated_order_views (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assignment_id uuid NOT NULL,
  user_id uuid NOT NULL,
  first_seen_at timestamp with time zone,
  dismissed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT provider_delegated_order_views_pkey PRIMARY KEY (id),
  CONSTRAINT provider_delegated_order_views_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.booking_team_assignments(id),
  CONSTRAINT provider_delegated_order_views_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.provider_delegation_connection_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid NOT NULL,
  requester_provider_id uuid NOT NULL,
  recipient_provider_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text, 'cancelled'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  responded_at timestamp with time zone,
  CONSTRAINT provider_delegation_connection_requests_pkey PRIMARY KEY (id),
  CONSTRAINT provider_delegation_connection_requests_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.provider_delegation_requests(id),
  CONSTRAINT provider_delegation_connection_reque_requester_provider_id_fkey FOREIGN KEY (requester_provider_id) REFERENCES public.profiles(id),
  CONSTRAINT provider_delegation_connection_reque_recipient_provider_id_fkey FOREIGN KEY (recipient_provider_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.provider_delegation_request_targets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid NOT NULL,
  recipient_provider_id uuid NOT NULL,
  match_score numeric,
  notified_at timestamp with time zone,
  delivery_status text NOT NULL DEFAULT 'queued'::text CHECK (delivery_status = ANY (ARRAY['queued'::text, 'sent'::text, 'failed'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT provider_delegation_request_targets_pkey PRIMARY KEY (id),
  CONSTRAINT provider_delegation_request_targets_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.provider_delegation_requests(id),
  CONSTRAINT provider_delegation_request_targets_recipient_provider_id_fkey FOREIGN KEY (recipient_provider_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.provider_delegation_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  requester_provider_id uuid NOT NULL,
  service_tag_ids ARRAY NOT NULL DEFAULT '{}'::uuid[],
  radius_km integer NOT NULL DEFAULT 80 CHECK (radius_km >= 1 AND radius_km <= 200),
  urgency text NOT NULL DEFAULT 'normal'::text CHECK (urgency = ANY (ARRAY['normal'::text, 'urgent'::text])),
  request_center_latitude double precision,
  request_center_longitude double precision,
  time_window_start timestamp with time zone,
  time_window_end timestamp with time zone,
  terms_note text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'paused'::text, 'closed'::text, 'expired'::text])),
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  service_category_ids ARRAY NOT NULL DEFAULT '{}'::uuid[],
  CONSTRAINT provider_delegation_requests_pkey PRIMARY KEY (id),
  CONSTRAINT provider_delegation_requests_requester_provider_id_fkey FOREIGN KEY (requester_provider_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.provider_ledger_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  booking_id uuid,
  entry_type text NOT NULL CHECK (entry_type = ANY (ARRAY['credit_pending'::text, 'credit_available'::text, 'debit_withdrawal'::text, 'hold'::text, 'release_hold'::text, 'adjustment'::text])),
  amount numeric NOT NULL,
  currency text NOT NULL DEFAULT 'usd'::text,
  reference_type text,
  reference_id text,
  note text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  stripe_event_id text,
  stripe_payment_intent_id text,
  stripe_charge_id text,
  evidence_status text NOT NULL DEFAULT 'unverified'::text CHECK (evidence_status = ANY (ARRAY['unverified'::text, 'verified'::text, 'reversed'::text])),
  CONSTRAINT provider_ledger_entries_pkey PRIMARY KEY (id),
  CONSTRAINT provider_ledger_entries_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.profiles(id),
  CONSTRAINT provider_ledger_entries_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.provider_points (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL UNIQUE,
  balance integer NOT NULL DEFAULT 0 CHECK (balance >= 0),
  lifetime_purchased integer NOT NULL DEFAULT 0 CHECK (lifetime_purchased >= 0),
  lifetime_spent integer NOT NULL DEFAULT 0 CHECK (lifetime_spent >= 0),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT provider_points_pkey PRIMARY KEY (id),
  CONSTRAINT provider_points_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.provider_team_group_members (
  group_id uuid NOT NULL,
  member_id uuid NOT NULL,
  added_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT provider_team_group_members_pkey PRIMARY KEY (group_id, member_id),
  CONSTRAINT provider_team_group_members_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.provider_team_groups(id),
  CONSTRAINT provider_team_group_members_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.provider_team_groups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL,
  name text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT provider_team_groups_pkey PRIMARY KEY (id),
  CONSTRAINT provider_team_groups_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.provider_team_invites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invite_code text NOT NULL UNIQUE,
  inviter_id uuid NOT NULL,
  invitee_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text, 'expired'::text])),
  owner_share numeric NOT NULL DEFAULT 70.00,
  message text,
  responded_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT provider_team_invites_pkey PRIMARY KEY (id),
  CONSTRAINT provider_team_invites_inviter_id_fkey FOREIGN KEY (inviter_id) REFERENCES public.profiles(id),
  CONSTRAINT provider_team_invites_invitee_id_fkey FOREIGN KEY (invitee_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.provider_team_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL,
  member_id uuid NOT NULL,
  owner_share numeric NOT NULL DEFAULT 70.00,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT provider_team_links_pkey PRIMARY KEY (id),
  CONSTRAINT provider_team_links_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.profiles(id),
  CONSTRAINT provider_team_links_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.provider_withdrawals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  amount numeric NOT NULL,
  currency text NOT NULL DEFAULT 'usd'::text,
  status text NOT NULL DEFAULT 'requested'::text CHECK (status = ANY (ARRAY['requested'::text, 'processing'::text, 'paid'::text, 'failed'::text, 'canceled'::text])),
  requested_at timestamp with time zone NOT NULL DEFAULT now(),
  processed_at timestamp with time zone,
  stripe_payout_id text UNIQUE,
  failure_reason text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT provider_withdrawals_pkey PRIMARY KEY (id),
  CONSTRAINT provider_withdrawals_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.push_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  body text NOT NULL,
  data jsonb DEFAULT '{}'::jsonb,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'retry'::text, 'sent'::text, 'failed'::text])),
  attempts integer DEFAULT 0,
  last_error text,
  created_at timestamp with time zone DEFAULT now(),
  processed_at timestamp with time zone,
  event_type text,
  entity_type text,
  entity_id uuid,
  dedupe_key text,
  not_before timestamp with time zone DEFAULT now(),
  priority smallint DEFAULT 5,
  CONSTRAINT push_queue_pkey PRIMARY KEY (id),
  CONSTRAINT push_queue_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.ranking_config_v1 (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  surface text NOT NULL,
  key text NOT NULL,
  value double precision NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ranking_config_v1_pkey PRIMARY KEY (id)
);
CREATE TABLE public.recommendation_events_v1 (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  session_id text,
  surface text NOT NULL,
  event_type text NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid NOT NULL,
  service_id uuid,
  video_id uuid,
  query_text text,
  position integer,
  score double precision,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT recommendation_events_v1_pkey PRIMARY KEY (id),
  CONSTRAINT recommendation_events_v1_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT recommendation_events_v1_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT recommendation_events_v1_video_id_fkey FOREIGN KEY (video_id) REFERENCES public.videos(id)
);
CREATE TABLE public.referral_attributions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  referred_user_id uuid NOT NULL UNIQUE,
  affiliate_user_id uuid NOT NULL,
  claim_id uuid,
  attribution_source text NOT NULL CHECK (attribution_source = ANY (ARRAY['deep_link'::text, 'android_referrer'::text, 'ios_deferred'::text, 'manual_code'::text, 'unknown'::text])),
  attributed_at timestamp with time zone NOT NULL DEFAULT now(),
  locked_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT referral_attributions_pkey PRIMARY KEY (id),
  CONSTRAINT referral_attributions_referred_user_id_fkey FOREIGN KEY (referred_user_id) REFERENCES public.profiles(id),
  CONSTRAINT referral_attributions_affiliate_user_id_fkey FOREIGN KEY (affiliate_user_id) REFERENCES public.profiles(id),
  CONSTRAINT referral_attributions_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.pending_referral_claims(id)
);
CREATE TABLE public.referral_clicks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  click_id text NOT NULL UNIQUE,
  affiliate_user_id uuid NOT NULL,
  affiliate_code text,
  ip_address text,
  user_agent text,
  platform_hint text,
  referer_url text,
  click_token text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT referral_clicks_pkey PRIMARY KEY (id),
  CONSTRAINT referral_clicks_affiliate_user_id_fkey FOREIGN KEY (affiliate_user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.report_case_actions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  actor_id uuid NOT NULL,
  action_type text NOT NULL CHECK (action_type = ANY (ARRAY['triaged'::text, 'investigation_started'::text, 'request_more_info'::text, 'resolved'::text, 'rejected'::text, 'escalated'::text, 'refund_requested'::text, 'refund_approved'::text, 'refund_rejected'::text, 'refund_processed'::text])),
  note text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT report_case_actions_pkey PRIMARY KEY (id),
  CONSTRAINT report_case_actions_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.report_cases(id),
  CONSTRAINT report_case_actions_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.report_case_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  actor_id uuid,
  event_type text NOT NULL,
  note text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT report_case_events_pkey PRIMARY KEY (id),
  CONSTRAINT report_case_events_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.report_cases(id),
  CONSTRAINT report_case_events_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.report_case_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  sender_id uuid,
  sender_role text NOT NULL CHECK (sender_role = ANY (ARRAY['reporter'::text, 'admin'::text, 'system'::text])),
  body text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  attachment_path text,
  attachment_mime text,
  attachment_size_bytes bigint,
  CONSTRAINT report_case_messages_pkey PRIMARY KEY (id),
  CONSTRAINT report_case_messages_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.report_cases(id),
  CONSTRAINT report_case_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.report_case_threads (
  case_id uuid NOT NULL,
  reporter_id uuid NOT NULL,
  admin_owner_id uuid,
  last_message_preview text,
  last_message_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT report_case_threads_pkey PRIMARY KEY (case_id),
  CONSTRAINT report_case_threads_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.report_cases(id),
  CONSTRAINT report_case_threads_reporter_id_fkey FOREIGN KEY (reporter_id) REFERENCES public.profiles(id),
  CONSTRAINT report_case_threads_admin_owner_id_fkey FOREIGN KEY (admin_owner_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.report_cases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  reporter_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['dispute'::text, 'user_abuse'::text, 'service_issue'::text, 'payment_issue'::text, 'safety_incident'::text, 'other'::text])),
  target_type text NOT NULL DEFAULT 'booking'::text,
  target_id uuid,
  booking_id uuid,
  reported_user_id uuid,
  status text NOT NULL DEFAULT 'submitted'::text CHECK (status = ANY (ARRAY['submitted'::text, 'triaged'::text, 'investigating'::text, 'awaiting_parties'::text, 'resolved'::text, 'rejected'::text, 'closed'::text, 'escalated'::text])),
  severity text NOT NULL DEFAULT 'medium'::text CHECK (severity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  priority text NOT NULL DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])),
  subject text,
  description text NOT NULL,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  resolution_summary text,
  refund_status text NOT NULL DEFAULT 'not_requested'::text CHECK (refund_status = ANY (ARRAY['not_requested'::text, 'requested'::text, 'under_review'::text, 'approved'::text, 'rejected'::text, 'processed'::text])),
  admin_owner_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  resolved_at timestamp with time zone,
  CONSTRAINT report_cases_pkey PRIMARY KEY (id),
  CONSTRAINT report_cases_reporter_id_fkey FOREIGN KEY (reporter_id) REFERENCES public.profiles(id),
  CONSTRAINT report_cases_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT report_cases_reported_user_id_fkey FOREIGN KEY (reported_user_id) REFERENCES public.profiles(id),
  CONSTRAINT report_cases_admin_owner_id_fkey FOREIGN KEY (admin_owner_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid,
  service_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  provider_id uuid NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  review_text text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT reviews_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT reviews_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.profiles(id),
  CONSTRAINT reviews_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.saved_services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  service_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT saved_services_pkey PRIMARY KEY (id),
  CONSTRAINT saved_services_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT saved_services_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.service_availability (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  service_id uuid NOT NULL,
  day_of_week smallint NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT service_availability_pkey PRIMARY KEY (id),
  CONSTRAINT service_availability_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.service_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  image_url text,
  description text,
  is_popular boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  allow_images boolean NOT NULL DEFAULT true,
  requires_before_image boolean NOT NULL DEFAULT false,
  requires_after_image boolean NOT NULL DEFAULT false,
  CONSTRAINT service_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.service_photos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  photo_type text NOT NULL CHECK (photo_type = ANY (ARRAY['before'::text, 'after'::text])),
  photo_url text NOT NULL,
  uploaded_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_photos_pkey PRIMARY KEY (id),
  CONSTRAINT service_photos_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT service_photos_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.service_search_features_v1 (
  service_id uuid NOT NULL,
  provider_id uuid NOT NULL,
  category_id uuid,
  is_active boolean NOT NULL DEFAULT true,
  average_rating double precision NOT NULL DEFAULT 0,
  rating_count integer NOT NULL DEFAULT 0,
  completion_rate double precision NOT NULL DEFAULT 0,
  avg_response_minutes double precision NOT NULL DEFAULT 0,
  avg_completion_minutes double precision NOT NULL DEFAULT 0,
  quality_score double precision NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  impression_count integer NOT NULL DEFAULT 0,
  click_count integer NOT NULL DEFAULT 0,
  open_count integer NOT NULL DEFAULT 0,
  book_count integer NOT NULL DEFAULT 0,
  ctr double precision NOT NULL DEFAULT 0,
  open_rate double precision NOT NULL DEFAULT 0,
  book_rate double precision NOT NULL DEFAULT 0,
  engagement_score double precision NOT NULL DEFAULT 0,
  CONSTRAINT service_search_features_v1_pkey PRIMARY KEY (service_id),
  CONSTRAINT service_search_features_v1_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.service_categories(id),
  CONSTRAINT service_search_features_v1_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT service_search_features_v1_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.service_tag_map (
  service_id uuid NOT NULL,
  tag_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT service_tag_map_pkey PRIMARY KEY (service_id, tag_id),
  CONSTRAINT service_tag_map_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT service_tag_map_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.service_tags(id)
);
CREATE TABLE public.service_tags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  label text NOT NULL,
  category_id uuid,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT service_tags_pkey PRIMARY KEY (id),
  CONSTRAINT service_tags_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.service_categories(id)
);
CREATE TABLE public.services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  category_id uuid,
  title text NOT NULL,
  short_description text,
  full_description text,
  cover_image_url text,
  gallery_image_urls ARRAY DEFAULT '{}'::text[],
  base_price numeric NOT NULL,
  pricing_type text NOT NULL CHECK (pricing_type = ANY (ARRAY['fixed'::text, 'hourly'::text, 'per_visit'::text])),
  location_type text NOT NULL CHECK (location_type = ANY (ARRAY['provider_location'::text, 'customer_location'::text, 'online'::text])),
  service_radius_km integer,
  estimated_duration_minutes integer,
  min_booking_notice_hours integer DEFAULT 4,
  max_daily_bookings integer DEFAULT 10,
  is_active boolean DEFAULT true,
  average_rating double precision DEFAULT 0,
  rating_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  price_min numeric NOT NULL DEFAULT 5,
  price_max numeric NOT NULL DEFAULT 500,
  booking_enabled boolean NOT NULL DEFAULT true,
  latitude double precision CHECK (latitude IS NULL OR latitude >= '-90'::integer::double precision AND latitude <= 90::double precision),
  longitude double precision CHECK (longitude IS NULL OR longitude >= '-180'::integer::double precision AND longitude <= 180::double precision),
  allow_images boolean,
  requires_before_image boolean,
  requires_after_image boolean,
  CONSTRAINT services_pkey PRIMARY KEY (id),
  CONSTRAINT services_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.profiles(id),
  CONSTRAINT services_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.service_categories(id)
);
CREATE TABLE public.threads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL,
  provider_id uuid NOT NULL,
  last_message_text text,
  last_message_time timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT threads_pkey PRIMARY KEY (id),
  CONSTRAINT threads_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.profiles(id),
  CONSTRAINT threads_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_notifications (
  id text NOT NULL,
  user_id uuid NOT NULL,
  category text NOT NULL DEFAULT 'system'::text,
  title text NOT NULL,
  body text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  dedupe_key text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  read_at timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT user_notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.video_boost_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  video_id uuid NOT NULL,
  provider_booster_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT video_boost_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT video_boost_campaigns_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.profiles(id),
  CONSTRAINT video_boost_campaigns_video_id_fkey FOREIGN KEY (video_id) REFERENCES public.videos(id),
  CONSTRAINT video_boost_campaigns_provider_booster_id_fkey FOREIGN KEY (provider_booster_id) REFERENCES public.provider_boosters(id)
);
CREATE TABLE public.video_comment_likes (
  comment_id uuid NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT video_comment_likes_pkey PRIMARY KEY (comment_id, user_id),
  CONSTRAINT video_comment_likes_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES public.video_comments(id),
  CONSTRAINT video_comment_likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.video_comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  video_id uuid NOT NULL,
  user_id uuid NOT NULL,
  parent_comment_id uuid,
  comment_text text NOT NULL CHECK (length(TRIM(BOTH FROM comment_text)) > 0 AND length(comment_text) <= 1000),
  likes_count integer NOT NULL DEFAULT 0 CHECK (likes_count >= 0),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT video_comments_pkey PRIMARY KEY (id),
  CONSTRAINT video_comments_video_id_fkey FOREIGN KEY (video_id) REFERENCES public.videos(id),
  CONSTRAINT video_comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT video_comments_parent_comment_id_fkey FOREIGN KEY (parent_comment_id) REFERENCES public.video_comments(id)
);
CREATE TABLE public.video_discovery_features_v1 (
  video_id uuid NOT NULL,
  provider_id uuid NOT NULL,
  service_id uuid NOT NULL,
  is_discoverable boolean NOT NULL DEFAULT false,
  recency_score double precision NOT NULL DEFAULT 0,
  quality_score double precision NOT NULL DEFAULT 0,
  boost_score double precision NOT NULL DEFAULT 0,
  discover_score double precision NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  impression_count integer NOT NULL DEFAULT 0,
  click_count integer NOT NULL DEFAULT 0,
  open_count integer NOT NULL DEFAULT 0,
  watch_count integer NOT NULL DEFAULT 0,
  book_count integer NOT NULL DEFAULT 0,
  ctr double precision NOT NULL DEFAULT 0,
  open_rate double precision NOT NULL DEFAULT 0,
  watch_rate double precision NOT NULL DEFAULT 0,
  book_rate double precision NOT NULL DEFAULT 0,
  engagement_score double precision NOT NULL DEFAULT 0,
  CONSTRAINT video_discovery_features_v1_pkey PRIMARY KEY (video_id),
  CONSTRAINT video_discovery_features_v1_video_id_fkey FOREIGN KEY (video_id) REFERENCES public.videos(id),
  CONSTRAINT video_discovery_features_v1_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.profiles(id),
  CONSTRAINT video_discovery_features_v1_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.videos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  service_id uuid NOT NULL,
  video_path text NOT NULL,
  thumbnail_path text,
  title text,
  description text,
  duration_seconds integer,
  aspect_ratio text DEFAULT '16:9'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  verification_state text NOT NULL DEFAULT 'UNVERIFIED'::text CHECK (verification_state = ANY (ARRAY['UNVERIFIED'::text, 'IDENTITY_VERIFIED'::text, 'LICENSE_VERIFIED'::text, 'RESTRICTED'::text, 'SUSPENDED'::text])),
  is_discoverable boolean NOT NULL DEFAULT false,
  display_order integer NOT NULL DEFAULT 0,
  compliance_reviewed boolean NOT NULL DEFAULT false,
  compliance_notes text,
  availability_synced_at timestamp with time zone,
  CONSTRAINT videos_pkey PRIMARY KEY (id),
  CONSTRAINT videos_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.profiles(id),
  CONSTRAINT videos_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.wallet_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  wallet_id uuid NOT NULL,
  booking_id uuid,
  type text NOT NULL CHECK (type = ANY (ARRAY['payment'::text, 'tip'::text, 'withdrawal'::text, 'refund'::text])),
  amount numeric NOT NULL,
  description text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT wallet_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT wallet_transactions_wallet_id_fkey FOREIGN KEY (wallet_id) REFERENCES public.wallets(id),
  CONSTRAINT wallet_transactions_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.wallets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  balance numeric DEFAULT 0,
  pending_balance numeric DEFAULT 0,
  total_earnings numeric DEFAULT 0,
  total_tips numeric DEFAULT 0,
  total_withdrawals numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT wallets_pkey PRIMARY KEY (id),
  CONSTRAINT wallets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
